name: Self-Hosted Test

on: [push]

jobs:
  run-on-self-hosted:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Running on a Windows self-hosted runner!"
